allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        google()
        mavenCentral()
    }
}

// Some Flutter plugins have their own buildscript repositories. Make the
// project mirror available to those plugin build scripts as well.
gradle.beforeProject { project ->
    project.buildscript.repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
